config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic.base import RedirectView, TemplateView

from devfolio.portfolio.sitemaps import ProjectSitemap

# A dictionary of sitemaps
sitemaps = {"projects": ProjectSitemap}

urlpatterns = [
    path("", include("devfolio.portfolio.urls", namespace="home")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("devfolio.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Home-made apps
    path("portfolio/", include("devfolio.portfolio.urls")),
    path(
        "robots.txt",
        TemplateView.as_view(
            template_name="pages/robots.txt", content_type="text/plain"
        ),
    ),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path(
        "favicon.ico",
        RedirectView.as_view(
            url=staticfiles_storage.url("img/favicons/favicon.ico")
        ),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

devfolio/portfolio/urls.py
from django.urls import path

from . import views

app_name = "portfolio"
urlpatterns = [
    path("", views.portfolio_home, name="home"),
    path("list/", views.portfolio_list, name="list"),
    path("<int:id>/", views.portfolio_detail, name="detail"),
]

devfolio/users/urls.py
from django.urls import path

from devfolio.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

devfolio/portfolio/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class Portfolio(models.Model):
    """Model describing Portfolio metadata."""

    # NOTE:
    # The three features image fields are configured as a FileField
    # instead of an ImageField, so they will also accept SVG, which is
    # not supported by Pillow (the third party library Django uses for
    # the ImageField).

    # NOTE:
    # Allowing SVG files can pose a security issue, since SVG files
    # can contain Javascript

    # Also see:
    # https://code.djangoproject.com/ticket/14092

    title = models.CharField(_("Title"), max_length=100)
    subtitle = models.CharField(_("Subtitle"), max_length=100, blank=True)
    description = models.TextField(
        _("Description"), max_length=300, blank=True
    )
    frontpage_greeting = models.CharField(
        _("Frontpage Greeting"), max_length=50, blank=True
    )
    featured_image = models.ImageField(
        _("Featured Image"),
        upload_to="images",
        blank=True,
    )
    resume = models.FileField(
        _("Resume"), upload_to="resume", max_length=100, blank=True
    )
    usp_main_image = models.ImageField(
        _("Unique Selling Points - Main Image"), upload_to="images", blank=True
    )
    usp1_title = models.CharField(
        _("Unique Selling Point 1 - Title"), max_length=30, blank=True
    )
    usp1_description = models.TextField(
        _("Unique Selling Point 1 - Description"), max_length=300, blank=True
    )
    usp1_image = models.FileField(
        _("Unique Selling Point 1 - Image"), upload_to="images", blank=True
    )
    usp2_title = models.CharField(
        _("Unique Selling Point 2 - Title"), max_length=30, blank=True
    )
    usp2_description = models.TextField(
        _("Unique Selling Point 2 - Description"), max_length=300, blank=True
    )
    usp2_image = models.FileField(
        _("Unique Selling Point 2 - Image"), upload_to="images", blank=True
    )
    usp3_title = models.CharField(
        _("Unique Selling Point 3 - Title"), max_length=30, blank=True
    )
    usp3_description = models.TextField(
        _("Unique Selling Point 3 - Description"), max_length=300, blank=True
    )
    usp3_image = models.FileField(
        _("Unique Selling Point 3 - Image"), upload_to="images", blank=True
    )
    # created = models.DateTimeField(auto_now_add=True)
    # updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        """Meta definition for Portfolio."""

        verbose_name = "Portfolio"
        verbose_name_plural = "Portfolios"

    def __str__(self):
        """Unicode representation of Portfolio."""
        return self.title

    def get_absolute_url(self):
        """Return absolute url for Portfolio."""
        return reverse("portfolio:home")


class Project(models.Model):
    """Model definition for Project."""

    title = models.CharField(_("Title"), max_length=100)
    subtitle = models.CharField(_("Subtitle"), max_length=100, blank=True)
    description = models.TextField(
        _("Description"), max_length=300, blank=True
    )
    featured_image = models.ImageField(_("Featured Image"), upload_to="images")
    date = models.DateField(_("Date"), default=timezone.now)
    client = models.CharField(_("Client"), max_length=50, blank=True)
    services = models.CharField(_("Services"), max_length=100, blank=True)
    client_url = models.URLField(_("Client URL"), max_length=200, blank=True)
    live_url = models.URLField(_("Live URL"), max_length=200, blank=True)
    live_url_message_modal_title = models.CharField(
        _("Live URL Popup Title"), max_length=50, blank=True
    )
    live_url_message_modal_text = models.TextField(
        _("Live URL Popup Message"), max_length=300, blank=True
    )
    repo_url = models.URLField(_("Repo URL"), max_length=200, blank=True)
    objective_text = models.TextField(
        _("Objective"), max_length=500, blank=True
    )
    tools_n_tech_text = models.TextField(
        _("Tools and Tech"), max_length=500, blank=True
    )
    challenge_text = models.TextField(
        _("Challenge"), max_length=500, blank=True
    )
    share_fb = models.BooleanField(_("Share on FaceBook"), default=False)
    share_twitter = models.BooleanField(_("Share on Twitter"), default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        """Meta definition for Project."""

        verbose_name = "Project"
        verbose_name_plural = "Projects"

    def __str__(self):
        """Unicode representation of Project."""
        return self.title

    def get_absolute_url(self):
        """Return absolute url for Project."""
        return reverse("portfolio:detail", kwargs={"id": self.id})


class Tag(models.Model):
    """Model definition for Tag."""

    title = models.CharField(_("Title"), max_length=15)
    project = models.ManyToManyField("Project", verbose_name=_("Project"))

    class Meta:
        """Meta definition for Tag."""

        verbose_name = "Tag"
        verbose_name_plural = "Tags"

    def __str__(self):
        """Unicode representation of Tag."""
        return self.title


class Screenshot(models.Model):
    """
    Model definition for Screenshot.
    One or more can optionally be attached to a Portfolio Project.
    """

    caption = models.CharField(_("Caption"), max_length=50)
    screenshot = models.ImageField(_("Screenshot"), upload_to="screenshots")
    project = models.ForeignKey(
        "Project",
        verbose_name=_("Project"),
        on_delete=models.CASCADE,
    )

    class Meta:
        """Meta definition for Screenshot."""

        verbose_name = "Screenshot"
        verbose_name_plural = "Screenshots"

    def __str__(self):
        """Unicode representation of Screenshot."""
        return f"{self.project}: {self.caption}"


class VideoURL(models.Model):
    """
    Model definition for VideoURL.
    One or more can optionally be attached to a Portfolio Project.
    """

    caption = models.CharField(_("Caption"), max_length=50)
    url = models.URLField(_("Video URL"), max_length=200)
    screenshot = models.ImageField(_("Screenshot"), upload_to="screenshots")
    project = models.ForeignKey(
        "Project",
        verbose_name=_("Project"),
        on_delete=models.CASCADE,
    )

    class Meta:
        """Meta definition for VideoURL."""

        verbose_name = "VideoURL"
        verbose_name_plural = "VideoURLs"

    def __str__(self):
        """Unicode representation of VideoURL."""
        return f"{self.project}: {self.caption}"

devfolio/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for DevFolio."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

devfolio/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

devfolio/portfolio/views.py
import re

from django.shortcuts import get_object_or_404, render

from .models import Portfolio, Project, Tag

# Hard-code the main portfolio (for now)
portfolio = Portfolio.objects.first()


def portfolio_home(request):
    items = Project.objects.all().order_by('-date')
    tags = Tag.objects.all()
    tag_titles = [tag.title.lower() for tag in tags]
    return render(
        request,
        "pages/home.html",
        {
            "portfolio": portfolio,
            "items": items,
            "tags": tags,
            "tag_titles": tag_titles,
        },
    )


def portfolio_list(request):
    return render(request, "portfolio/list.html", {"navbar_dark": True})


def portfolio_detail(request, id):
    project = get_object_or_404(Project, id=id)
    related = Project.objects.exclude(id=id)
    screenshots = project.screenshot_set.all().order_by('id')

    # Prepare URL's for display
    live_url_short = ""
    repo_url_short = ""
    if project.live_url:
        regex_pattern = r"https?://([\w\d\.-]+)"  # Match only sld.domain.tld
        result = re.search(regex_pattern, project.live_url)
        if result:
            live_url_short = result.group(1)
    if project.repo_url:
        regex_pattern = r"https?://([\w\d\.-]+)/(.+)"  # Match only repo name
        result = re.search(regex_pattern, project.repo_url)
        if result:
            repo_url_short = result.group(2)

    return render(
        request,
        "portfolio/detail.html",
        {
            "portfolio": portfolio,
            "navbar_floating": True,
            "project": project,
            "related": related,
            "screenshots": screenshots,
            "live_url_short": live_url_short,
            "repo_url_short": repo_url_short,
        },
    )

devfolio/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

devfolio/templates/portfolio/detail.html
            {% extends "base.html" %}
            {% load static i18n %}

            {% block vendor_styles %}
            <link rel="stylesheet" media="screen" href="{% static 'css/tiny-slider.css' %}" />
            <link rel="stylesheet" media="screen" href="{% static 'css/lightgallery.min.css' %}" />
            {% endblock vendor_styles %}

            {% block page_content %}
            <!-- Page content-->
            <section class="sidebar-enabled sidebar-end" style="margin-top: -120px;">
                <div class="container">
                    <div class="row">
                        <!-- Project description-->
                        <div class="col-lg-4 sidebar pt-5 pt-lg-7 order-lg-2">
                            <div class="px-sm-4 pt-6 py-lg-6 position-relative zindex-5">
                                <h1 class="h2">{{ project.title }}</h1>
                                <p class="fs-sm">{{ project.subtitle }}</p>
                                <div class="d-sm-flex align-items-center pb-2 mb-5 border-bottom fs-sm">
                                    <div class="d-flex align-items-center mb-3">
                                        <div class="text-nowrap text-muted me-3"><i class="ai-calendar me-1"></i><span>{{ project.date|date:"F Y" }}</span></div>
                                        {% if project.tag_set.all %}
                                        <div class="text-nowrap text-muted"><i class="ai-tag me-1"></i><span>{% for tag in project.tag_set.all %}{{ tag.title }}{% if not forloop.last %}, {% endif %}{% endfor %}</span></div>
                                        {% endif %}
                                    </div>
                                    <a class="btn btn-translucent-primary btn-sm ms-auto mb-3 d-inline-block d-lg-none" href="#gallery" data-scroll>Project Gallery</a>
                                </div>
                                {% if project.client %}
                                <h3 class="h5">Client</h3>
                                {% else %}
                                <h3 class="h5">Project Details</h3>
                                {% endif %}
                                <ul class="list-unstyled fs-md mb-4 pb-2">
                                    {% if project.client %}
                                    <li class="mb-2">
                                        {% if project.client_url %}
                                        Name:<a class="nav-link-style ms-2" href="{{ project.client_url }}" target="_blank" rel="noopener">{{ project.client }}</a>
                                        {% else %}
                                        Name:<span class="fw-medium text-nav ms-2">{{ project.client }}</span>
                                        {% endif %}
                                    </li>
                                    {% endif %}
                                    {% if project.services %}
                                    <li class="mb-2">Services:<span class="fw-medium text-nav ms-2">{{ project.services }}</span></li>
                                    {% endif %}
                                    {% if live_url_short %}
                                    {% if project.live_url_message_modal_text %}
                                    <li data-bs-toggle="modal" data-bs-target="#messageModal">
                                        <i class="ai-globe" alt="Live URL"></i>
                                        <a class="nav-link-style ms-2" data-bs-toggle="tooltip" data-bs-placement="right" title="Check it out live!">{{ live_url_short }}</a>
                                    </li>
                                    {% else %}
                                    <li>
                                        <i class="ai-globe" alt="Live URL"></i>
                                        <a class="nav-link-style ms-2" href="{{ project.live_url }}" target="_blank" rel="noopener" data-bs-toggle="tooltip" data-bs-placement="right" title="Check it out live!">{{ live_url_short }}</a>
                                    </li>
                                    {% endif %}
                                    {% endif %}
                                    {% if repo_url_short %}
                                    <li><i class="ai-github"></i><a class="nav-link-style ms-2" href="{{ project.repo_url }}" target="_blank" rel="noopener" data-bs-toggle="tooltip" data-bs-placement="right" title="Check out the source code!">{{ repo_url_short }}</a></li>
                                    {% endif %}
                                </ul>
                                <h3 class="h5">Objective</h3>
                                <p class="fs-sm mb-4 pb-2">{{ project.objective_text }}</p>
                                <h3 class="h5">Tools &amp; Technologies</h3>
                                <p class="fs-sm mb-4 pb-2">{{ project.tools_n_tech_text }}</p>
                                <h3 class="h5">Challenge</h3>
                                <p class="fs-sm mb-4 pb-2">{{ project.challenge_text }}</p>
                                <h3 class="h5">Share</h3>
                                {% if project.share_fb %}
                                <a class="btn-social bs-outline bs-facebook me-2 my-2" href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" target="_blank" rel="noopener">
                                    <i class="ai-facebook"></i>
                                </a>
                                {% endif %}
                                {% if project.share_twitter %}
                                <a class="btn-social bs-outline bs-twitter me-2 my-2" href="https://twitter.com/intent/tweet?url={{ request.build_absolute_uri }}" target="_blank" rel="noopener">
                                    <i class="ai-twitter"></i>
                                </a>
                                {% endif %}
                            </div>
                        </div>
                        <!-- Project gallery (List)-->
                        <div class="col-lg-8 content pt-2 pt-lg-7 pb-lg-4 order-lg-1" id="gallery">
                            <div class="gallery pt-5 pb-4 py-lg-5">
                                {% if project.videourl_set.all %}
                                <!-- Video -->
                                {% for video in project.videourl_set.all %}
                                <a href="{{ video.url }}" class="gallery-item gallery-video rounded-3 mb-grid-gutter" data-sub-html='<h6 class="fs-sm text-light">{{ video.caption }}</h6>'>
                                    <img src="{{ video.screenshot.url }}" alt="{{ video.caption }}">
                                    <span class="gallery-caption">{{ video.caption }}</span>
                                </a>
                                {% endfor %}
                                {% endif %}
                                {% if screenshots %}
                                {% for screenshot in screenshots %}
                                <a class="gallery-item rounded-3 mb-grid-gutter" href="{{ screenshot.screenshot.url }}">
                                    <img src="{{ screenshot.screenshot.url }}" alt="{{ screenshot.caption }}">
                                    <span class="gallery-caption">{{ screenshot.caption }}</span>
                                </a>
                                {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {% if related %}
            <!-- Related projects (Carousel)-->
            <section class="border-top py-5 py-lg-6">
                <div class="container py-3 py-md-0">
                    <h2 class="h3 text-center mb-5">Related projects</h2>
                    <div class="tns-carousel-wrapper">
                        <div class="tns-carousel-inner" data-carousel-options="{&quot;items&quot;: 2, &quot;controls&quot;: false, &quot;nav&quot;: true, &quot;responsive&quot;: {&quot;0&quot;:{&quot;items&quot;:1, &quot;gutter&quot;: 16},&quot;500&quot;:{&quot;items&quot;:2, &quot;gutter&quot;: 16}, &quot;780&quot;:{&quot;items&quot;:3, &quot;gutter&quot;: 16}, &quot;1000&quot;:{&quot;items&quot;:4, &quot;gutter&quot;: 23}}}">
                            {% for project in related %}
                            <!-- Item-->
                            <div class="pb-2">
                                <div class="card card-curved-body shadow card-slide mx-1">
                                    <div class="card-slide-inner">
                                        <img class="card-img" src="{{ project.featured_image.url }}" alt="{{ project.title }}">
                                        <a class="card-body text-center" href="{{ project.get_absolute_url }}">
                                            <h3 class="h5 nav-heading mt-1 mb-2">{{ project.title }}</h3>
                                            <p class="fs-sm text-muted mb-1"><i class="ai-tag me-1"></i><span>{% for tag in project.tag_set.all %}{{ tag.title }}{% if not forloop.last %}, {% endif %}{% endfor %}</span></p>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div> <!-- /.tns-carousel-inner -->
                    </div> <!-- /.tns-carousel-wrapper -->
                </div> <!-- /.container -->
            </section>
            {% endif %}

            {% endblock page_content %}

            {% if project.live_url_message_modal_text %}
            {% block modal %}
            {% include 'partials/_message_modal.html' %}
            {% endblock modal %}
            {% endif %}

            {% block vendor_scripts %}
            <script src="{% static 'js/tiny-slider.js' %}"></script>
            <script src="{% static 'js/lightgallery.min.js' %}"></script>
            <script src="{% static 'js/lg-fullscreen.min.js' %}"></script>
            <script src="{% static 'js/lg-zoom.min.js' %}"></script>
            <script src="{% static 'js/lg-video.min.js' %}"></script>
            {% endblock vendor_scripts %}

            {% if project.live_url_message_modal_text %}
            {% block inline_javascript %}
            <script>
                // When user closes the modal, open the project demo URL in
                // a new tab/window (depends on user's browser setting).
                document.querySelector('#closeModal').addEventListener(
                    "click", () => {
                        window.open('{{ project.live_url }}', '_blank');
                    }
                );
            </script>
            {% endblock inline_javascript %}
            {% endif %}